### ISSUE TITLE
Reorganize config structure to group site information together

### ISSUE THREAD

**Issue by grosscol** [Landis-Lewis-Lab/goals-of-care#31]
Under the report configuration, all the information to be tied to a site id should be under that site id.  The current implementation has the site id required to be used as a key twice under each report type (clc and hbpc).  The only time a site ID should be repeated is if it exists as both a CLC and HBPC site.

```yaml
---
default:
  clc:
    assists:
      - "Data collected quarterly."
      - "Data is analyzed in aggregate."
      - "Your millage may vary."
    sites:
      449AE:
        name: "Bar Location Name"
        provider: "FeedBack Project"
        contact: "Jane Smith, Project Coordinator (jsmith@example.com)"
      5888:
        name: "Foo Location Name"
        provider: "Report Provider Group"
        contact:
          - "Ann Smith, Project Owner (asmith@example.com)"
          - "Bob Jones, Site Coordinator (jones2@example.com)"
  hbpc:
    assists:
      - "Data collected quarterly."
      - "Data is analyzed in aggregate."
      - "Your millage may vary."
    sites:
      5888:
        name: "Foo Location Name"
        provider: "Report Provider Group"
        contact:
          - "Ann Smith, Project Owner (asmith@example.com)"
          - "Carol James, Site Coordinator (cjam@example.com)"
      B1234:
        name: "Boop Location Name"
        provider: "Erin McReporter, Director of Reporting"
        contact: "Danna Smith, Project Coordinator (dsmith@example.com)"

```
