### ISSUE TITLE
modify default text for memo From: field

### ISSUE THREAD

**Issue by zachll** [Landis-Lewis-Lab/goals-of-care#71]
For CLC and HBPC sites that use the default "From: Long-Term Care QUERI project", change the text to "From: Long-Term Care QUERI program".

Update this also for sites that have two names, such as "Long-Term Care QUERI project and ... X"

**Comment by grosscol** [comment]
## Current state
The content of the from field is currently pulled from the provider specified in the config for the site.
In the template:
```tex
\memofrom{ \Sexpr{provider} }
```
Gets the provider from the config for the site. E.g.:
```yml
      6309AB:
        name: St. Albans Campus of the VA NY Harbor Healthcare System
        provider: "Long-Term Care QUERI project"
        contacts: "John Doe, Project Coordinator (johndoe@example.com)"
```
## Questions
Should the text "From: Long-Term Care QUERI program" be hard coded and no longer depend on the config?

> Update this also for sites that have two names

Is this a feature request to handle multiple entries in site name?  If so, that can be it's own ticket as all the places that reference the `name` from a site's config will have to accommodate such a change.

**Comment by grosscol** [comment]
Implemented some logic to calculate the content of the from field.  When testing with the provided VA config, discovered that the config already accounted for multiple providers at some sites.  E.g.

```yml
      5689AA:
        name: "VA Black Hills - Fort Meade"
        provider: "Long-Term Care QUERI project and Jane Doe"
        contacts: "Jane Doe 555-555-5555 ext 5555"
```
The config field for provider has already be used for two providers.

Emailed James & Winifred about changing QUERI project to QUERY program in their config. 

Made the corresponding changes in my local config so that example reports will have expected copy.
